
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: pixtr_development
test:
  <<: *default
  database: pixtr_test
production:
  <<: *default
  database: pixtr_production
  username: pixtr
  password: <%= ENV['PIXTR_DATABASE_PASSWORD'] %>
